name: Test Noop
run-name: "ghacron noop test (${{ github.event_name }})"

on:
  # ghacron: "TZ=Asia/Tokyo 30 2 * * 2"
  workflow_dispatch:

jobs:
  noop:
    runs-on: ubuntu-24.04
    steps:
      - run: echo "ghacron dispatched at $(date -u)"
